Compile with -Wall -Werror compiler flags
Add the compiler flags to display all compiler warnings to CMakeLists.txt, and
fixes the resulting warnings.

This compiler flags detected that the some of the case statements in the main.c
getopt switch didn't have a break statement, causing the control flow to
fall-through to the next case. In this case the lack of break statements
appears to have been intended by the original developer. Regardless, the
control flow has been modified to allow a 'break' after every case statement to
ensure any future typos are caught and fixed at compile time instead of causing
unintended behavior.

Also detected the lack of the sin_zero field, but this is less important.  In
testing, compiling with -Wpedantic produced a void pointer arithmetic warning,
among many  __VA_ARGS__ is a GNU extension variadic macro warnings.  Due to the
risk of undefined behavior with non-gcc compilers the void pointer arithmetic
has been cast to char*.

main.c:125:27: error: this statement may fall through
[-Werror=implicit-fallthrough=] options.debug = 1;

nbd.c:327:5: error: missing initializer for field 'sin_zero' of 'struct
sockaddr_in' [-Werror=missing-field-initializers]

io.h:42:20: warning: pointer of type 'void *' used in arithmetic
[-Wpointer-arith] dest   +=  once_read;

For completeness, I note that compiling with clang produced the following
-Wunused-function error, but the function may be useful in the future so I
chose not to fix this -Werror warning.

nbd.c:108:22: error: unused function 'get16' [-Werror,-Wunused-function]
static inline status get16(int sock, u16 *v) {
                     ^